"""默认命令沙箱注册表数据。"""

from __future__ import annotations

from app.tools.sandbox_registry_types import ToolMetadata, ToolSafetyLevel


DEFAULT_TOOL_REGISTRY: dict[str, ToolMetadata] = {
    "pwd": ToolMetadata(
        name="pwd",
        description="打印当前工作目录",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["pwd"],
    ),
    "date": ToolMetadata(
        name="date",
        description="显示当前日期时间",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["date", 'date +"%Y-%m-%d %H:%M:%S"'],
    ),
    "echo": ToolMetadata(
        name="echo",
        description="输出文本",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["echo hello", 'echo "multi word text"'],
    ),
    "whoami": ToolMetadata(
        name="whoami",
        description="显示当前用户名",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["whoami"],
    ),
    "hostname": ToolMetadata(
        name="hostname",
        description="显示主机名",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["hostname"],
    ),
    "uname": ToolMetadata(
        name="uname",
        description="显示系统信息",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["uname -a"],
    ),
    "uptime": ToolMetadata(
        name="uptime",
        description="显示系统运行时间",
        safety_level=ToolSafetyLevel.SAFE,
        category="info",
        examples=["uptime"],
    ),
    "ls": ToolMetadata(
        name="ls",
        description="列出目录内容",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["ls", "ls -la", "ls src/"],
        max_timeout_seconds=10.0,
    ),
    "cat": ToolMetadata(
        name="cat",
        description="查看文件内容",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["cat file.txt", "cat README.md"],
        max_timeout_seconds=15.0,
    ),
    "find": ToolMetadata(
        name="find",
        description="搜索文件",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="filesystem",
        examples=["find . -name '*.py'", "find src -type f"],
        max_timeout_seconds=30.0,
    ),
    "grep": ToolMetadata(
        name="grep",
        description="在文件中搜索文本",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["grep 'TODO' *.py", "grep -r pattern src/"],
        max_timeout_seconds=20.0,
    ),
    "head": ToolMetadata(
        name="head",
        description="显示文件开头",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["head -20 file.py", "head -n 50 README.md"],
    ),
    "tail": ToolMetadata(
        name="tail",
        description="显示文件末尾",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["tail -20 file.py", "tail -f log.txt"],
        max_timeout_seconds=15.0,
    ),
    "wc": ToolMetadata(
        name="wc",
        description="统计行数/字数/字节数",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["wc -l file.py", "wc -c file.txt"],
    ),
    "diff": ToolMetadata(
        name="diff",
        description="比较文件差异",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["diff a.txt b.txt", "diff -u old.py new.py"],
        max_timeout_seconds=15.0,
    ),
    "tree": ToolMetadata(
        name="tree",
        description="以树形结构显示目录",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["tree", "tree -L 2 src/", "tree -a --prune"],
        max_timeout_seconds=10.0,
    ),
    "file": ToolMetadata(
        name="file",
        description="识别文件类型",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["file mystery.bin", "file *"],
    ),
    "du": ToolMetadata(
        name="du",
        description="查看磁盘使用量",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["du -sh .", "du -h --max-depth=1"],
        max_timeout_seconds=15.0,
    ),
    "df": ToolMetadata(
        name="df",
        description="查看磁盘空间",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["df -h"],
    ),
    "stat": ToolMetadata(
        name="stat",
        description="查看文件详细状态",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["stat file.txt"],
    ),
    "readlink": ToolMetadata(
        name="readlink",
        description="读取符号链接目标",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["readlink -f path"],
    ),
    "basename": ToolMetadata(
        name="basename",
        description="提取文件名",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["basename /path/to/file.txt"],
    ),
    "dirname": ToolMetadata(
        name="dirname",
        description="提取目录路径",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["dirname /path/to/file.txt"],
    ),
    "realpath": ToolMetadata(
        name="realpath",
        description="获取绝对路径",
        safety_level=ToolSafetyLevel.SAFE,
        category="filesystem",
        examples=["realpath ./src/app.py"],
    ),
    "git": ToolMetadata(
        name="git",
        description="版本控制（只读操作自动放行，写操作需要审批）",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["git status", "git log --oneline -10", "git diff", "git branch -a", "git remote -v", "git show HEAD"],
        max_timeout_seconds=30.0,
    ),
    "python": ToolMetadata(
        name="python",
        description="运行 Python 脚本/表达式",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=['python -c "print(42)"', "python --version", "python script.py", "python -m py_compile file.py"],
        max_timeout_seconds=60.0,
    ),
    "pip": ToolMetadata(
        name="pip",
        description="Python 包管理器（仅列表/查询）",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["pip list", "pip show package-name", "pip --version"],
        max_timeout_seconds=60.0,
    ),
    "npm": ToolMetadata(
        name="npm",
        description="Node.js 包管理器（仅列表/查询）",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["npm list", "npm --version"],
        max_timeout_seconds=60.0,
    ),
    "node": ToolMetadata(
        name="node",
        description="运行 Node.js 脚本",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["node --version", "node script.js"],
        max_timeout_seconds=60.0,
    ),
    "make": ToolMetadata(
        name="make",
        description="构建工具",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["make", "make test", "make lint"],
        max_timeout_seconds=120.0,
    ),
    "pytest": ToolMetadata(
        name="pytest",
        description="Python 测试运行器",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["pytest", "pytest tests/ -v", "pytest tests/test_x.py -x"],
        max_timeout_seconds=120.0,
    ),
    "clang": ToolMetadata(
        name="clang/gcc",
        description="C/C++ 编译器（仅编译不链接）",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["gcc -fsyntax-only file.c"],
        max_timeout_seconds=30.0,
    ),
    "rustc": ToolMetadata(
        name="rustc",
        description="Rust 编译器（仅检查语法）",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["rustc --edition 2021 --emit=metadata file.rs"],
        max_timeout_seconds=30.0,
    ),
    "go": ToolMetadata(
        name="go",
        description="Go 工具链",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="dev",
        examples=["go version", "go vet ./...", "go build -o /dev/null ."],
        max_timeout_seconds=120.0,
    ),
    "curl": ToolMetadata(
        name="curl",
        description="HTTP 客户端",
        safety_level=ToolSafetyLevel.DANGEROUS,
        category="network",
        examples=["curl -I https://example.com", "curl https://api.example.com/data"],
        max_timeout_seconds=30.0,
    ),
    "wget": ToolMetadata(
        name="wget",
        description="文件下载工具",
        safety_level=ToolSafetyLevel.DANGEROUS,
        category="network",
        examples=["wget -qO- url"],
        max_timeout_seconds=60.0,
    ),
    "ping": ToolMetadata(
        name="ping",
        description="网络连通性测试",
        safety_level=ToolSafetyLevel.DANGEROUS,
        category="network",
        examples=["ping -c 3 8.8.8.8"],
        max_timeout_seconds=15.0,
    ),
    "nslookup": ToolMetadata(
        name="nslookup",
        description="DNS 查询",
        safety_level=ToolSafetyLevel.DANGEROUS,
        category="network",
        examples=["nslookup example.com"],
        max_timeout_seconds=10.0,
    ),
    "ssh": ToolMetadata(name="ssh", description="远程连接（默认禁用）", safety_level=ToolSafetyLevel.BLOCKED, category="network", examples=[]),
    "scp": ToolMetadata(name="scp", description="远程复制（默认禁用）", safety_level=ToolSafetyLevel.BLOCKED, category="network", examples=[]),
    "cp": ToolMetadata(
        name="cp",
        description="复制文件",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="system",
        examples=["cp a.txt b.txt", "cp -r dir1/ dir2/"],
        max_timeout_seconds=30.0,
    ),
    "mv": ToolMetadata(
        name="mv",
        description="移动/重命名文件",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="system",
        examples=["mv old.txt new.txt"],
        max_timeout_seconds=15.0,
    ),
    "mkdir": ToolMetadata(
        name="mkdir",
        description="创建目录",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="system",
        examples=["mkdir new_dir"],
        max_timeout_seconds=5.0,
    ),
    "touch": ToolMetadata(
        name="touch",
        description="创建空文件或更新时间戳",
        safety_level=ToolSafetyLevel.RESTRICTED,
        category="system",
        examples=["touch newfile.txt"],
        max_timeout_seconds=5.0,
    ),
    "chmod": ToolMetadata(
        name="chmod",
        description="修改权限（受限）",
        safety_level=ToolSafetyLevel.DANGEROUS,
        category="system",
        examples=["chmod +x script.sh"],
        max_timeout_seconds=5.0,
    ),
    "rm": ToolMetadata(
        name="rm",
        description="删除文件（严格限制：禁止 rm -rf / 和递归根目录）",
        safety_level=ToolSafetyLevel.DANGEROUS,
        category="system",
        examples=["rm file.txt", "rm -rf my_temp_dir/"],
        max_timeout_seconds=15.0,
    ),
    "kill": ToolMetadata(name="kill", description="发送信号给进程（默认禁用）", safety_level=ToolSafetyLevel.BLOCKED, category="system", examples=[]),
    "sudo": ToolMetadata(name="sudo", description="超级用户权限（永久禁用）", safety_level=ToolSafetyLevel.BLOCKED, category="system", examples=[]),
}
